# Created with YamlCreate.ps1 v2.5.0 $debug=NVS2.CRLF.5-1-26100-1591.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: DarkAlex17.GMan
PackageVersion: 0.0.2
InstallerType: zip
Commands:
- gman
Installers:
- Architecture: x64
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: gman.exe
    PortableCommandAlias: gman
  InstallerUrl: https://github.com/Dark-Alex-17/gman/releases/download/v0.0.2/gman-x86_64-pc-windows-msvc.zip
  InstallerSha256: 62E2151386396CE877C8B88790BEACD12F6038BB36D555C9ED254D43CF05DEC1
- Architecture: arm64
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: gman.exe
    PortableCommandAlias: gman
  InstallerUrl: https://github.com/Dark-Alex-17/gman/releases/download/v0.0.2/gman-aarch64-pc-windows-msvc.zip
  InstallerSha256: 81EBF8CA54D0D43DCFD1DCF563649C37507722696657DF3E8746370B5DBCB293
ManifestType: installer
ManifestVersion: 1.10.0
