# Created with YamlCreate.ps1 v2.5.0 $debug=NVS2.CRLF.5-1-26100-1591.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.10.0.schema.json

PackageIdentifier: DarkAlex17.GMan
PackageVersion: 0.0.2
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.10.0
